sonar.projectKey=joshiel123_UCV-SI-lab9
sonar.organization=joshiel123
sonar.projectName=UCV-SI-lab9

sonar.sources=travel_assistant
sonar.tests=tests
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml