name: CI Pipeline

on:
  pull_request:
    branches:
      - develop
      - main
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop
      - main

jobs:
  quality-check:
    name: Quality and Security Assessment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run Ruff
        run: poetry run ruff check .

      # AQUÍ ESTÁ EL CAMBIO (Las líneas env y GOOGLE_API_KEY)
      - name: Run Pytest
        env:
          GOOGLE_API_KEY: "clave_falsa"
        run: poetry run pytest --cov=travel_assistant --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
